// use websocket server and listen to client connects
// message responses will be echoed in uppercase

// 1. setup HTTP server: python -m SimpleHTTPServer
// 2. setup WebSocket sttreaming server: node stream-test.js
// 3. open localhost:8000 and click -> connects
//    - this opens a socket connection - server responds by writes data (Binay/blob style)


// TODO: Try using WebRTC which will hopefully manage the traffic better


const SOCKET_PORT = 8080;

var bytesWritten = 0;
var readableStream = require('./dummy-streamer'); // use a dummy streamer for testing
var ws = require("nodejs-websocket");

/**
  SOCKET SERVER
  **/

var server = ws.createServer().listen(SOCKET_PORT);
server.on("error", function(error) {
    console.log("Server Error");
});
server.on("connection", function(conn) {
  console.log("New connection");
  conn.on("text", function (str) {
    var strArr = str.split('-');
    var command = strArr[0];
    switch(command){
      case 'pause':
        if(!readableStream.isPaused())
          readableStream.pause();
        else
          readableStream.resume();
        break;
      case 'rate':
        var rate = strArr[1].replace('-', '');
        readableStream.setRate(parseInt(rate));
        break;
      default:
        console.log(`received: ${str}`);
    }
    // if(str == "pause") {
    //   // stop sending samples - but maintain connections
    //
    // } else {
    //   console.log(`received: ${str}`);
    // }
  });
  conn.on("close", function (code, reason) {
    console.log("Connection closed");
    readableStream.end();
    readableStream.destroy();
  });
  conn.on("error", function (error) {
    console.log("Connection Error");
    readableStream.end();
    readableStream.destroy();
  });


  /**
    READBALE STREAM
    **/
  readableStream.start();
  readableStream.getStream().on('data', function(chunk) {
      //console.log(`connection readystate ${conn.readyState}`);
      if(conn.readyState == 3) {
        readableStream.endStreamer();
        return;
      }
      //console.log(`writing ${chunk.length}bytes of data`);
      //data += chunk;
      conn.sendBinary(chunk);
      bytesWritten += chunk.length;
  });
  readableStream.getStream().on('error', function(error) {
      console.log(`error was generated by readable: ${error.message} - ${error.code}`);
      console.log(`${error.stack}`);
  });
  readableStream.getStream().on('end', function(){
    console.log(`readable file ended... ending writeable.. ${bytesWritten} bytes written`);
    writableStream.end();
    //readableStream = null;
    bytesWritten = 0;
  });


});





// var Readable = require('stream').Readable,
//     util = require('util');
//
// var MyReadStream = function() {
//   Readable.call(this, {objectMode: true});
//   //this.data = data;
//   this.curIndex = 0;
// };
// util.inherits(MyReadStream, Readable);

// var app = require('express')();
// var http = require('http').Server(app);
// var io = require('socket.io')(http);
// var port = process.env.PORT || 8001;
//
// app.get('/', function(req, res){
//   res.sendFile(__dirname + '/index.html');
// });
//
// io.on('connection', function(socket){
//   socket.on('chat message', function(msg){
//     io.emit('chat message', msg);
//   });
// });
//
// http.listen(port, function(){
//   console.log('listening on *:' + port);
// });
